ALTER TABLE clientes ADD COLUMN cep VARCHAR(9);
ALTER TABLE clientes ADD COLUMN logradouro VARCHAR(255);
ALTER TABLE clientes ADD COLUMN bairro VARCHAR(255);
ALTER TABLE clientes ADD COLUMN cidade VARCHAR(255);
ALTER TABLE clientes ADD COLUMN uf VARCHAR(2);
